### ISSUE TITLE
Model extraction problem

### ISSUE THREAD

**Issue by yanglpo** [Joshimello/SnowbreakModel#1]
Friend, I would like to ask you how to open the pak file of the game, I used the key and fmodel tools published online, but the tool reminded me of the key error, if possible, I hope you can guide me

**Comment by Joshimello** [comment]
Wussap, you are half way there! I think the assets are packed in a custom format, I used a tool "Quickbms" to unpack the assets with the key. The unpacked files can be viewed with fmodel without key after that. There is a lot more info [here](https://cs.rin.ru/forum/viewtopic.php?f=10&t=100672) fyi!
